import jsPDF from "jspdf";

const COLORS: Record<string, [number, number, number]> = {
  primary: [79, 70, 229],
  black: [15, 15, 15],
  gray: [113, 113, 122],
  lightGray: [161, 161, 170],
  white: [255, 255, 255],
  divider: [39, 39, 42],
};

const MARGIN = { left: 20, right: 20, top: 20 };
const PAGE_WIDTH = 210;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN.left - MARGIN.right;
const FOOTER_TEXT = "Generated by NextStep AI";

export interface PdfMetadata {
  title: string;
  careerGoal?: string;
  preferredIndustry?: string;
  experienceLevel?: string;
  generatedAt?: Date;
}

function addFooter(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.gray);
    doc.setFont("helvetica", "normal");
    doc.text(
      `${FOOTER_TEXT}  •  Page ${i} of ${pageCount}`,
      PAGE_WIDTH / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: "center" }
    );
  }
}

function renderFormattedText(
  doc: jsPDF,
  text: string,
  x: number,
  y: number,
  baseFontSize: number,
  baseColor: [number, number, number],
  maxWidth?: number
): number {
  const pageHeight = doc.internal.pageSize.getHeight();
  const maxContentY = pageHeight - 25;
  const width = maxWidth ?? CONTENT_WIDTH - (x - MARGIN.left);
  const lineHeight = baseFontSize * 0.7;
  const cleanText = text.replace(/\*\*/g, "").replace(/`/g, "");
  const lines = doc.splitTextToSize(cleanText, width);

  if (y + lines.length * lineHeight > maxContentY) {
    doc.addPage();
    y = MARGIN.top;
  }

  doc.setFont("helvetica", "normal");
  doc.setFontSize(baseFontSize);
  doc.setTextColor(...baseColor);
  doc.text(lines, x, y);

  return y + lines.length * lineHeight;
}

export function generatePdf(
  markdownContent: string,
  filename: string,
  metadata: PdfMetadata
) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageHeight = doc.internal.pageSize.getHeight();
  const maxContentY = pageHeight - 25;

  let y = MARGIN.top;

  // ── Header ──
  doc.setFillColor(...COLORS.primary);
  doc.rect(0, 0, PAGE_WIDTH, 36, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(...COLORS.white);
  doc.text("NextStep AI", MARGIN.left, 16);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(200, 200, 220);
  doc.text("AI-Powered Career Guidance", MARGIN.left, 23);

  doc.setFontSize(9);
  const headerRightText = metadata.generatedAt
    ? `Generated: ${metadata.generatedAt.toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
        hour: "2-digit",
        minute: "2-digit",
      })}`
    : `Generated: ${new Date().toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
        hour: "2-digit",
        minute: "2-digit",
      })}`;
  doc.text(headerRightText, PAGE_WIDTH - MARGIN.right, 23, { align: "right" });

  y = 44;

  // ── Document Title ──
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(...COLORS.black);
  doc.text(metadata.title, MARGIN.left, y);
  y += 10;

  // ── Metadata Box ──
  const metaItems: { label: string; value: string }[] = [];
  if (metadata.careerGoal) {
    metaItems.push({ label: "Career Goal", value: metadata.careerGoal });
  }
  if (metadata.preferredIndustry) {
    metaItems.push({ label: "Industry", value: metadata.preferredIndustry });
  }
  if (metadata.experienceLevel) {
    metaItems.push({ label: "Experience Level", value: metadata.experienceLevel });
  }

  if (metaItems.length > 0) {
    const boxHeight = metaItems.length * 7 + 8;
    doc.setFillColor(245, 245, 245);
    doc.roundedRect(MARGIN.left, y, CONTENT_WIDTH, boxHeight, 2, 2, "F");

    let metaY = y + 6;
    for (const item of metaItems) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(...COLORS.gray);
      doc.text(`${item.label}:`, MARGIN.left + 4, metaY);

      doc.setFont("helvetica", "normal");
      doc.setTextColor(...COLORS.black);
      const labelWidth = doc.getTextWidth(`${item.label}:  `);
      doc.text(item.value, MARGIN.left + 4 + labelWidth, metaY);
      metaY += 7;
    }
    y = metaY + 4;
  }

  // ── Divider ──
  doc.setDrawColor(...COLORS.divider);
  doc.setLineWidth(0.3);
  doc.line(MARGIN.left, y, PAGE_WIDTH - MARGIN.right, y);
  y += 6;

  // ── Parse and render markdown content ──
  const lines = markdownContent.split("\n");
  let i = 0;

  while (i < lines.length) {
    const line = lines[i];

    if (y > maxContentY) {
      doc.addPage();
      y = MARGIN.top;
    }

    // Skip empty lines
    if (line.trim() === "") {
      y += 3;
      i++;
      continue;
    }

    // Code block
    if (line.trim().startsWith("```")) {
      i++;
      const codeLines: string[] = [];
      while (i < lines.length && !lines[i].trim().startsWith("```")) {
        codeLines.push(lines[i]);
        i++;
      }
      i++; // skip closing ```

      if (codeLines.length > 0) {
        doc.setFillColor(245, 245, 245);
        const codeBlockHeight = codeLines.length * 4.5 + 6;
        const startY = y;
        if (y + codeBlockHeight > maxContentY) {
          doc.addPage();
          y = MARGIN.top;
        }
        doc.roundedRect(
          MARGIN.left,
          startY,
          CONTENT_WIDTH,
          codeBlockHeight,
          1,
          1,
          "F"
        );
        let codeY = startY + 5;
        doc.setFont("courier", "normal");
        doc.setFontSize(8);
        doc.setTextColor(...COLORS.black);
        for (const codeLine of codeLines) {
          doc.text(codeLine, MARGIN.left + 4, codeY);
          codeY += 4.5;
        }
        y = startY + codeBlockHeight + 3;
      }
      continue;
    }

    // Table detection
    if (line.trim().startsWith("|")) {
      const tableLines: string[] = [];
      while (i < lines.length && lines[i].trim().startsWith("|")) {
        if (!lines[i].trim().match(/^\|[\s\-:|]+\|$/)) {
          tableLines.push(lines[i]);
        }
        i++;
      }

      if (tableLines.length > 0) {
        const rows = tableLines.map((tl) =>
          tl
            .split("|")
            .filter((c) => c.trim() !== "")
            .map((c) => c.trim())
        );
        const colCount = Math.max(...rows.map((r) => r.length));
        const colWidth = CONTENT_WIDTH / colCount;
        const rowHeight = 7;

        if (y + rows.length * rowHeight > maxContentY) {
          doc.addPage();
          y = MARGIN.top;
        }

        rows.forEach((row, rowIdx) => {
          const bgColor: [number, number, number] =
            rowIdx === 0
              ? COLORS.primary
              : rowIdx % 2 === 0
                ? [245, 245, 245]
                : [255, 255, 255];

          doc.setFillColor(...bgColor);
          doc.rect(MARGIN.left, y, CONTENT_WIDTH, rowHeight, "F");

          row.forEach((cell, colIdx) => {
            doc.setFont("helvetica", rowIdx === 0 ? "bold" : "normal");
            doc.setFontSize(8);
            const textColor: [number, number, number] = rowIdx === 0 ? [...COLORS.white] : [...COLORS.black];
            doc.setTextColor(...textColor);
            doc.text(cell, MARGIN.left + colIdx * colWidth + 2, y + 5);
          });

          y += rowHeight;
        });

        doc.setDrawColor(...COLORS.divider);
        doc.setLineWidth(0.1);
        doc.rect(MARGIN.left, y - rows.length * rowHeight, CONTENT_WIDTH, rows.length * rowHeight);
        y += 3;
      }
      continue;
    }

    // H1 heading
    if (line.startsWith("# ") && !line.startsWith("## ")) {
      y += 2;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(16);
      doc.setTextColor(...COLORS.black);
      const headingText = line.replace(/^#\s+/, "").replace(/\*\*/g, "");
      const headingLines = doc.splitTextToSize(headingText, CONTENT_WIDTH);
      doc.text(headingLines, MARGIN.left, y);
      y += headingLines.length * 6.5 + 3;
      i++;
      continue;
    }

    // H2 heading
    if (line.startsWith("## ")) {
      y += 2;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(13);
      doc.setTextColor(...COLORS.primary);
      const headingText = line.replace(/^##\s+/, "").replace(/^\d+\.\s*/, "").replace(/\*\*/g, "");
      const headingLines = doc.splitTextToSize(headingText, CONTENT_WIDTH);
      doc.text(headingLines, MARGIN.left, y);
      y += headingLines.length * 5.5 + 1;

      doc.setDrawColor(...COLORS.primary);
      doc.setLineWidth(0.5);
      doc.line(MARGIN.left, y, MARGIN.left + 30, y);
      y += 4;
      i++;
      continue;
    }

    // H3 heading
    if (line.startsWith("### ")) {
      y += 1;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      doc.setTextColor(...COLORS.black);
      const headingText = line.replace(/^###\s+/, "").replace(/\*\*/g, "");
      const headingLines = doc.splitTextToSize(headingText, CONTENT_WIDTH);
      doc.text(headingLines, MARGIN.left, y);
      y += headingLines.length * 5 + 2;
      i++;
      continue;
    }

    // H4-H6 heading
    if (line.match(/^#{4,6}\s/)) {
      y += 1;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(...COLORS.black);
      const headingText = line.replace(/^#{4,6}\s+/, "").replace(/\*\*/g, "");
      const headingLines = doc.splitTextToSize(headingText, CONTENT_WIDTH);
      doc.text(headingLines, MARGIN.left, y);
      y += headingLines.length * 4.5 + 2;
      i++;
      continue;
    }

    // Horizontal rule
    if (line.trim().match(/^[-*_]{3,}$/)) {
      y += 2;
      doc.setDrawColor(...COLORS.divider);
      doc.setLineWidth(0.3);
      doc.line(MARGIN.left, y, PAGE_WIDTH - MARGIN.right, y);
      y += 4;
      i++;
      continue;
    }

    // Bullet list
    if (line.trim().startsWith("- ") || line.trim().startsWith("* ")) {
      const bulletText = line.trim().replace(/^[-*]\s+/, "");
      const cleanText = bulletText.replace(/\*\*/g, "").replace(/`/g, "");

      const textX = MARGIN.left + 8;
      const textWidth = CONTENT_WIDTH - 8;
      const lineHeight = 10 * 0.7;
      const wrappedLines = doc.splitTextToSize(cleanText, textWidth);

      if (y + wrappedLines.length * lineHeight > maxContentY) {
        doc.addPage();
        y = MARGIN.top;
      }

      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(...COLORS.black);
      doc.text("•", MARGIN.left + 2, y);
      doc.text(wrappedLines, textX, y);

      y += wrappedLines.length * lineHeight + 3.5;
      i++;
      continue;
    }

    // Numbered list
    if (line.trim().match(/^\d+[\.\)]\s/)) {
      const match = line.trim().match(/^(\d+[\.\)]\s+)(.*)/);
      if (match) {
        const number = match[1];
        const cleanText = match[2].replace(/\*\*/g, "").replace(/`/g, "");

        const numberWidth = doc.getTextWidth(number);
        const textX = MARGIN.left + 4 + numberWidth;
        const textWidth = CONTENT_WIDTH - (textX - MARGIN.left);
        const lineHeight = 10 * 0.7;
        const wrappedLines = doc.splitTextToSize(cleanText, textWidth);

        if (y + wrappedLines.length * lineHeight > maxContentY) {
          doc.addPage();
          y = MARGIN.top;
        }

        doc.setFont("helvetica", "bold");
        doc.setFontSize(10);
        doc.setTextColor(...COLORS.primary);
        doc.text(number, MARGIN.left + 2, y);

        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        doc.setTextColor(...COLORS.black);
        doc.text(wrappedLines, textX, y);

        y += wrappedLines.length * lineHeight + 1;
      }
      i++;
      continue;
    }

    // Blockquote
    if (line.trim().startsWith("> ")) {
      const quoteText = line.trim().replace(/^>\s+/, "").replace(/\*\*/g, "");
      const quoteX = MARGIN.left + 6;
      const quoteWidth = CONTENT_WIDTH - 10;
      const lineHeight = 10 * 0.7;
      const quoteLines = doc.splitTextToSize(quoteText, quoteWidth);

      if (y + quoteLines.length * lineHeight > maxContentY) {
        doc.addPage();
        y = MARGIN.top;
      }

      doc.setFillColor(...COLORS.primary);
      doc.rect(MARGIN.left, y - 3, 1.5, 5, "F");

      doc.setFont("helvetica", "italic");
      doc.setFontSize(10);
      doc.setTextColor(...COLORS.gray);
      doc.text(quoteLines, quoteX, y);
      y += quoteLines.length * lineHeight + 3;
      i++;
      continue;
    }

    // Regular paragraph
    const cleanText = line.replace(/\*\*/g, "").replace(/`/g, "");
    y = renderFormattedText(doc, cleanText, MARGIN.left, y, 10, COLORS.black);
    y += 1.5;
    i++;
  }

  // ── Footer ──
  addFooter(doc);

  doc.save(filename);
}
